### ISSUE TITLE
Use watch in swift upload container instead of poll loop

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#11]

**Comment by umohnani8** [comment]
**Description:**
When the image processing container is running, the data is pulled from SWIFT and put into the emptydir on the host.
During this process, the upload container constantly polls the API (every 5/10 seconds) to check whether the image processing container is still running. If the image processing container is done, the data in the emptydir is put back into SWIFT.
This issue wants to use watch - where the upload container watches the API for any changes instead of polling it every few seconds.
