### ISSUE TITLE
Scale out pman

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#8]
The biggest concern here is the /tmp/pman datastore.  We have a few options to solve this:

1) Remove the need for /tmp/pman.  Instead we could make calls to the OpenShift API to get the necessary status information.  The main problem with this is the status call to pman will need a little more info than it does today or some assumptions will need to be made.  Namely, the information about what cluster type the run call was made to isn't sent in the status call.
2) We could also change (or add an option) to have /tmp/pman use a proper datastore instead (Ex: postgresql).  This change would also require to not keep the values in memory.

The goal is to try to accomplish 1)

There could be an issue with not being able to get the status of jobs that have been pruned (particularly in swarm).

**Comment by danmcp** [comment]
@rudolphpienaar I think we need you to form an opinion on the best course of action.

**Comment by rudolphpienaar** [comment]
Right now I'm not a fan of adding yet-another dependency in the form of a database, esp since the main django backend already databases this information.

There were a few reasons that pman uses /tmp/pman and internal state/memory for status checking:

/tmp/pman
* Was initially envisioned to just capture internal memory state out to disk for persistency esp debugging

internal "db" to keep job state:
* Initially, with normal shell jobs (which is what pman was originally designed to manage), there is of course no concept of asking some service about job state.
* With container schedulers, keeping state of finished jobs in pman saved in theory the needs to do a REST call to a service

Need to keep thinking...
